#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'version-1.5',
 'build_date': '2014-12-10 18:10:51 +1100',
 'clean': None,
 'date': '2014-12-10 18:05:49 +1100',
 'revision_id': 'ben@benfinney.id.au-20141210070549-cr1evwf20o1jczn8',
 'revno': '229'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)s' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
